{{- if .Values.geminiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: agentgateway-secrets
  labels:
    app: agentgateway
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.geminiApiKey | quote }}
{{- end }}
